#include <iostem.hpp>

START_CODE
	FULL_NUMBER PIN EQ 1337;
	FULL_NUMBER INPUT EQ 0;
AGAIN:
	SAY "ENTER THE PIN TO CONTINUE: ";
	LISTEN INPUT;

	SPINNER OPEN 60 CLOSE;

	IF OPEN INPUT == PIN CLOSE {
		SAY GREEN "PIN IS CORRECT" THEN RESET_COLOR NEWLINE
		MOVETO END;
	}
	else {
		SAY RED THEN "PIN IS NOT CORRECT" THEN RESET_COLOR NEWLINE
		WAIT OPEN 500 CLOSE;
		MOVETO AGAIN;
	}
END:
	END_CODE	
