#include "iostem.hpp"
START_CODE
    FULL_NUMBER A = 0;
    FULL_NUMBER B = 0;
    FULL_NUMBER C = 0;
    SPINNER(120);
    SAY "TYPE NUMBER A: ";
    LISTEN A;
    SAY "TYPE NUMBER B: ";
    LISTEN B;
    SAY "A * B is " THEN A * B NEWLINE;

    SAY "TYPE NUMBER C: ";
    LISTEN C;

    IF OPEN C IsBIGGER A*B CLOSE {
        SAY GREEN THEN "OK" THEN RESET_COLOR NEWLINE;
    }
    OTHERWISE {
        SAY RED THEN "TOO SMALL" THEN RESET_COLOR NEWLINE;
    }

    SAY "RANDOMLY GENERATED NUMBER FROM -7 to 623: " THEN GREEN THEN RANDOM OPEN -7, 623 CLOSE THEN RESET_COLOR NEWLINE
    SAY "RANDOMLY GENERATED NUMBER FROM -6.72 to 1.41: " THEN GREEN THEN RANDOM_FLOAT OPEN -6.72f, 1.41f CLOSE THEN RESET_COLOR NEWLINE
    SAY RED THEN "RED" THEN RESET_COLOR NEWLINE;
    SAY BLACK THEN "BLACK" THEN RESET_COLOR NEWLINE;
    SAY GREEN THEN "GREEN" THEN RESET_COLOR NEWLINE;
    SAY YELLOW THEN "YELLOW" THEN RESET_COLOR NEWLINE;
    SAY BLUE THEN "BLUE" THEN RESET_COLOR NEWLINE;
    SAY MAGENTA THEN "MAGENTA" THEN RESET_COLOR NEWLINE;
    SAY CYAN THEN "CYAN" THEN RESET_COLOR NEWLINE;
    SAY WHITE THEN "WHITE" THEN RESET_COLOR NEWLINE;

    WORDS sixword{"THIS TEXT IS PRINTED OUT SLOWLY"};
    SAY SLOWLY OPEN sixword CLOSE NEWLINE;
END_CODE
